import Navbar from "@/components/Navbar";
import "./globals.css";
import Head from "next/head";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Nombre de tu Negocio - Servicio Principal</title>
        <meta name="description" content="Descubre nuestros servicios en Nombre de tu Negocio. Ofrecemos soluciones efectivas para [tu industria]." />
        <link rel="canonical" href="https://www.ejemplo.com/" />
      </Head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
